### ISSUE TITLE
Que tal começarmos a ultilizar TypeScript?

### ISSUE THREAD

**Issue by diogojorgebasso** [Taaaaaar/stunning-octo-spork#1]
Acho que seria legal ultilizarmos de maneira bem simples o TypeScript, numa nova branch, por exemplo, para iniciantes começarem a pegar traquejo. Além de que, oferece importante benefícios ao OpenSoftware de acordo com o [Diego Fernandes - vídeo no YT linkado](https://www.youtube.com/watch?v=0mYq5LrQN1s).

Aguardo ansiosamente por resposta, cordialmente.

**Comment by TarcisioPhilips** [comment]
Muito legal sua sugestão, vamos sim!
